# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180507_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='toc',
            field=models.TextField(default=b''),
        ),
    ]
