# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_toc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='toc',
        ),
    ]
